/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Controller;
import model.Slovo;
import nitii.ObradaKlijentskihZahteva;
import nitii.PokreniServer;
import operacija.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author vldmrk
 */
public class ServerskaForma extends javax.swing.JFrame {

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        Controller.getInstance().setSf(this);
        pokreni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxReci = new javax.swing.JComboBox<>();
        jTextFieldSlovo1 = new javax.swing.JTextField();
        jTextFieldSlovo2 = new javax.swing.JTextField();
        jTextFieldSlovo3 = new javax.swing.JTextField();
        jTextFieldSlovo4 = new javax.swing.JTextField();
        jTextFieldSlovo5 = new javax.swing.JTextField();
        jLabelKorisnik1 = new javax.swing.JLabel();
        jLabelKorisnik2 = new javax.swing.JLabel();
        jButtonPokreniIgru = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Izaberi reč:");

        jLabelKorisnik1.setText("jLabel2");

        jLabelKorisnik2.setText("jLabel2");

        jButtonPokreniIgru.setText("POKRENI");
        jButtonPokreniIgru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPokreniIgruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxReci, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPokreniIgru, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelKorisnik2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelKorisnik1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(jTextFieldSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxReci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSlovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSlovo5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSlovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSlovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSlovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonPokreniIgru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabelKorisnik1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelKorisnik2)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPokreniIgruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPokreniIgruActionPerformed
        String odabranaRec = (String) jComboBoxReci.getSelectedItem();
        Controller.getInstance().setOdabranaRec(odabranaRec);
        Controller.getInstance().setPokrenuto(true);
        jTextFieldSlovo1.setText(String.valueOf(odabranaRec.charAt(0)));
        jTextFieldSlovo2.setText(String.valueOf(odabranaRec.charAt(1)));
        jTextFieldSlovo3.setText(String.valueOf(odabranaRec.charAt(2)));
        jTextFieldSlovo4.setText(String.valueOf(odabranaRec.charAt(3)));
        jTextFieldSlovo5.setText(String.valueOf(odabranaRec.charAt(4)));
        jButtonPokreniIgru.setEnabled(false);
        jComboBoxReci.setEnabled(false);
    }//GEN-LAST:event_jButtonPokreniIgruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPokreniIgru;
    private javax.swing.JComboBox<String> jComboBoxReci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelKorisnik1;
    private javax.swing.JLabel jLabelKorisnik2;
    private javax.swing.JTextField jTextFieldSlovo1;
    private javax.swing.JTextField jTextFieldSlovo2;
    private javax.swing.JTextField jTextFieldSlovo3;
    private javax.swing.JTextField jTextFieldSlovo4;
    private javax.swing.JTextField jTextFieldSlovo5;
    // End of variables declaration//GEN-END:variables

    private void pokreni() {
        PokreniServer ps = new PokreniServer();
        ps.start();
        for (String rec : Controller.getInstance().getReci()) {
            jComboBoxReci.addItem(rec);
        }

        jTextFieldSlovo1.setEditable(false);
        jTextFieldSlovo2.setEditable(false);
        jTextFieldSlovo3.setEditable(false);
        jTextFieldSlovo4.setEditable(false);
        jTextFieldSlovo5.setEditable(false);

        jLabelKorisnik1.setText("Prvi korisnik: broj pokusaja/broj pogodjenih (0/0)");
        jLabelKorisnik2.setText("Drugi korisnik: broj pokusaja/broj pogodjenih (0/0)");
    }

    public void pogodjeno(Slovo s) {
        if (!Controller.getInstance().getPogodjenaSlova().contains(s)) {
            char c = s.getKarakter();
            int poz = s.getPozicija();
            switch (poz) {
                case 1:
                    jTextFieldSlovo1.setText(String.valueOf(c));
                    break;
                case 2:
                    jTextFieldSlovo2.setText(String.valueOf(c));
                    break;
                case 3:
                    jTextFieldSlovo3.setText(String.valueOf(c));
                    break;
                case 4:
                    jTextFieldSlovo4.setText(String.valueOf(c));
                    break;
                case 5:
                    jTextFieldSlovo5.setText(String.valueOf(c));
                    break;
                default:
                    throw new AssertionError();
            }
        }
    }
}
